### PR TITLE
XORShiftRandom and more tests

### PR DESCRIPTION
**Pull request by renatoathaydes**
Created XORShiftRandom.
Refactored tests so that any implementation of `Random` can be tested using the same test suite.
Added some more basic statistics tests.

### CODE REVIEW

**Comment by jvasileff** [comment]
Alternate implementations like `XORShiftRandom` would be _very_ useful, but it's not a goal for the `api` or `java` modules to expand in this way (much like `java.util` doesn't include all of the RNGs in http://maths.uncommons.org). Would you consider hosting an implementations module that I could link to in the readme? I could also rename the test module to `com.vasileff.ceylon.random.test.api` and share it on Herd.

Eventually, I hope that the api and java modules get rolled into the SDK, but any extras or implementations module would live on.

Also - I didn't realize you were working on this, so I have un-pushed changes to `next`, and worse, a rebase. Sorry! I'll push these soon, and also take a look at your test updates.

**Comment by jvasileff** [comment]
Also - it may actually be necessary to have _three_ implementations libraries - JVM, JS, and x-platform. Without using something like `xmath::Long`, it's really hard to write these things in a x-platform manner without making significant compromises and errors.

**Comment by renatoathaydes** [comment]
I had been working on Random in order to implement random test input in Specks... I had this code hanging around for a while, and thought it would be good to contribute to your project as you put some effort already designing the API and the LCG implementation... but ok, I can create another module that depends on yours and put it on Herd.

About platform issues, I tested my implementation of XORShift in JS and Java and it passes the tests in both as I accounted for the 32-bit issue in JS (by throwing away bits higher than the 32nd after shift operations, just like JS does)... is there any other problem you can see?

Regarding the test module, yeah, that would be cool.
But I think the convention is to name test modules starting with `test`, like

```
test.com.vasileff.ceylon.random
```

**Comment by jvasileff** [comment]
> another module

Great!

> About platform issues

No, I didn't notice any issues after a quick look. But applications may need faithful reproductions of well known and audited algorithms using whatever sized integers the algo was designed for. 2^32 is a pretty small number, and I'm not sure much is designed for 2^53, so there may be compromises or hard to detect faults.

> convention is to name test modules starting with test

Yes, but they are not usually published, so I'm wondering how @fromage would feel about that on Herd.

**Pull request closed without merging**
